version: "3.9"

services:
  postgres:
    image: docker.io/library/postgres:latest
    container_name: colmeia
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/database:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=colmeia
      - POSTGRES_PASSWORD=colmeia
      - POSTGRES_DB=app
      - TZ=America/Fortaleza
