global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'java-spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
        labels:
          application: projeto-colmeia