name: Security CI

on:
  push:
    branches:
      - develop

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 3. Configurar Cache do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 4. Configurar Cache do Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: 5. Executar Análises de Segurança e Gerar Relatórios
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B verify \
            org.owasp:dependency-check-maven:aggregate \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=api \
            -Dsonar.projectName='api' \
            -DskipTests

      # --- INÍCIO DA INTEGRAÇÃO COM DEFECTDOJO ---

      - name: 5. Enviar Relatório do Dependency-Check para o DefectDojo
        if: success()
        run: |
          curl -X POST \
            --insecure \
            --url "${{ secrets.DEFECT_DOJO_URL }}/api/v2/import-scan/" \
            --header "Authorization: Token ${{ secrets.DEFECT_DOJO_API_KEY }}" \
            --form "scan_type=Dependency Check Scan" \
            --form "product_name=colmeia-jogos-api" \
            --form "engagement_name=CI Build Dependency-Check ${{ github.run_id }}" \
            --form "file=@${{ github.workspace }}/target/dependency-check-report.xml" \
            --form "auto_create_context=true"

      - name: 6. Enviar Relatório do SpotBugs para o DefectDojo
        if: success()
        run: |
          curl -X POST \
            --insecure \
            --url "${{ secrets.DEFECT_DOJO_URL }}/api/v2/import-scan/" \
            --header "Authorization: Token ${{ secrets.DEFECT_DOJO_API_KEY }}" \
            --form "scan_type=SpotBugs Scan" \
            --form "product_name=colmeia-jogos-api" \
            --form "engagement_name=CI Build SpotBugs ${{ github.run_id }}" \
            --form "file=@${{ github.workspace }}/target/spotbugsXml.xml" \
            --form "auto_create_context=true"

      # Opcional: Você pode também fazer upload dos relatórios como artefatos
      - name: 8. Carregar Artefatos de Relatório
        if: always() # Executa mesmo se os passos anteriores falharem, para debug
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            target/dependency-check-report.xml
            target/spotbugsXml.xml
            target/bom.xml
